name: "publish"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    if: ${{ github.event.pull_request.merged }} && github.repository_owner == 'jamessizeland' # This is to ensure that only the owner can publish the app.
    name: "Publish Tauri App"
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # for Arm based macs (M1 and above).
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-24.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          # - platform: "windows-latest"
          #   args: ""
          - platform: "ubuntu-24.04" # For Android, also use a standard Ubuntu runner
            args: "--target aarch64-linux-android"
            build_type: "android"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        # Only run for the Linux desktop build, not the Android build (which also uses ubuntu-24.04 runner)
        if: matrix.platform == 'ubuntu-24.04' && matrix.args == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # --- Android Specific Setup ---
      - name: Set up JDK
        if: matrix.build_type == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: setup Android SDK and NDK
        # Condition on the specific Android build args
        if: matrix.build_type == 'android'
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
      - name: Configure Cargo and Environment for Android
        if: matrix.build_type == 'android'
        env:
          # ANDROID_NDK_HOME is set by `android-actions/setup-android`
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_HOME }} # Make it available to this step
        run: |
          echo "ANDROID_NDK_HOME is $ANDROID_NDK_HOME" # Verify it's set
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

          # Create .cargo/config.toml - This is the robust way
          mkdir -p .cargo
          cat << EOF > .cargo/config.toml
          [target.aarch64-linux-android]
          ar = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
          # Use API level 21 or your project's minSdk
          linker = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
          EOF
          echo "Created .cargo/config.toml:"
          cat .cargo/config.toml
      - name: setup Android signing
        # Condition on the specific Android build args
        if: matrix.build_type == 'android'
        run: |
          rustup target add aarch64-linux-android
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties
          echo "Keystore properties created."
          cd ../../.. # Go back to root

      - name: install frontend dependencies
        run: bun install # change this to npm, pnpm or bun depending on which one you use.

      - name: build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
